### ISSUE TITLE
Don't overwrite native Promise

### ISSUE THREAD

**Issue by aparshin** [mapbox/mapbox-sdk-js#113]
I use node v4.5.0, which supports native promises.

But when I use `mapbox` module, node's native promises are replaced with polyfill from `mapbox/vendor/promise.js`

Mapbox is just a part of my project, and I want to use native promises when it is possible.

Is it possible not to overwrite native promises by default?

Test case:
```
var mapbox = require('mapbox')
console.log(Promise) //Now it is polyfill
```

**Comment by tmcw** [comment]
Yep, I agree that this is much preferable. cc @scothis since this Promise implementation is there to support the `rest` library.

**Comment by tmcw** [comment]
Fixed in 5d4a382c85657194cbefaa49e5f7b2f73928c291

**Comment by chasemgray** [comment]
I still see this issue when loading the latest version. Angular 2 zones get a fatal error when trying to load the library.

**Comment by tmcw** [comment]
Can you

**Comment by scothis** [comment]
@chasemgray can you confirm you are running `1.0.0-beta5`?

Testing in the node REPL, I don't see an issue:

```
$ node
> var p = Promise
undefined
> require('mapbox')
{ [Function: service] getUser: [Function: getUser] }
> p === Promise
true
> 
```

**Comment by chasemgray** [comment]
We're using JSPM for module loading. I don't think you can conditionally load when using jSPM.

**Comment by davidtheclark** [comment]
The newly published `@mapbox/mapbox-sdk` prompts you to install your own Promise polyfill if you need one.
